"""跨模块复用的固定常量定义。"""

from __future__ import annotations

PROTOCOL_AUDIO_CODEC = "opus"
PROTOCOL_AUDIO_SAMPLE_RATE = 16000
PROTOCOL_AUDIO_CHANNELS = 1
PROTOCOL_AUDIO_FRAME_MS = 20
TTS_PROTOCOL_AUDIO_SAMPLE_RATE = 24000
TTS_PROTOCOL_AUDIO_CHANNELS = 1
TTS_PROTOCOL_AUDIO_FRAME_MS = 20
SUPPORTED_OPUS_FRAME_MS = (20, 40, 60)

KWS_MODEL_SAMPLE_RATE = 16000
FOLLOWUP_VAD_MODEL_SAMPLE_RATE = 16000

__all__ = [
    "FOLLOWUP_VAD_MODEL_SAMPLE_RATE",
    "KWS_MODEL_SAMPLE_RATE",
    "PROTOCOL_AUDIO_CHANNELS",
    "PROTOCOL_AUDIO_CODEC",
    "PROTOCOL_AUDIO_FRAME_MS",
    "PROTOCOL_AUDIO_SAMPLE_RATE",
    "SUPPORTED_OPUS_FRAME_MS",
    "TTS_PROTOCOL_AUDIO_CHANNELS",
    "TTS_PROTOCOL_AUDIO_FRAME_MS",
    "TTS_PROTOCOL_AUDIO_SAMPLE_RATE",
]
